INSERT INTO roster VALUES ("Nicholas Flores", "Prop", "6-0", "215", "Sophomore", "Carson City, CA");
INSERT INTO roster VALUES ("Kevin McCarron", "Loose Forward", "5-10", "195", "Senior", "Daly City, CA");
INSERT INTO roster VALUES ("Matt Large", "Scrumhalf", "5-7", "175", "Sophomore", "Manhattan Beach. CA");
INSERT INTO roster VALUES ("Issac Covarrubias", "Prop", "5-10", "193", "Junior", "Palm Springs, CA");
INSERT INTO roster VALUES ("David Fox", "Back", "5-11", "195", "Freshman", "Turlock, CA");
INSERT INTO roster VALUES ("Carlos Espinoza", "Wing", "6-0", "175", "Sophomore", "Coachella, CA");
INSERT INTO roster VALUES ("Pontus Arfwedson", "Lock", "6-2", "210", "Senior", "Uppsala, Sweden");
INSERT INTO roster VALUES ("Isaiah Ma", "Scrumhalf", "5-6", "190", "Junior", "San Jose, CA");
INSERT INTO roster VALUES ("Brandon Spoulos", "Lock", "6-3", "220", "Junior", "Discovery Bay, CA");
INSERT INTO roster VALUES ("Dylan Ennis", "Center", "5-10", "190", "Freshman", "San Francisco, CA");
INSERT INTO roster VALUES ("Brendan Hart", "Lock", "6-1", "190", "Senior", "Granite Bay, CA");
INSERT INTO roster VALUES ("Marcus Rafferty", "Back", "6-1", "170", "Junior", "Ireland");
INSERT INTO roster VALUES ("Aaron Turner", "Back", "5-10", "185", "Junior", "Compton, CA");
INSERT INTO roster VALUES ("Krishan Lad", "Loose Forward", "6-1", "193", "Junior", "San Jose, CA");
INSERT INTO roster VALUES ("Amanaki Veikoso", "Center", "6-0", "200", "Freshman", "Inglewood, CA");
INSERT INTO roster VALUES ("Henri Felsenstein", "Back", "6-2", "195", "Senior", "San Jose, CA");
INSERT INTO roster VALUES ("Ebi Apreala", "Forward", "6-0", "200", "Sophomore", "Inglewood, CA");
INSERT INTO roster VALUES ("Ismael Alvarez", "Back", "5-7", "195", "Junior", "Brentwood, CA");
INSERT INTO roster VALUES ("Carlos Loya", "Prop", "6-0", "250", "Junior", "San Diego, CA");
INSERT INTO roster VALUES ("Jeffrey Martinez", "Back", "5-8", "160", "Junior", "Chino Hills, CA");
INSERT INTO roster VALUES ("Aitalokahi Adeoye", "Forward", "6-2", "260", "Senior", "Palmdale, CA");
INSERT INTO roster VALUES ("Garrett Manoukian", "Center", "5-11", "200", "Senior", "Burbank, CA");
INSERT INTO roster VALUES ("Joseph Spoulos", "Wing", "5-9", "170", "Senior", "San Jose, CA");